# Site settings
title: czr
header-img: "img/lala.jpg"
tagline: "吉光片羽"  
description: "待我大神归来，娶你回家可好"  
baseurl: ""
url: "http://2016caicai.github.io"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Rick"
  email: 1196363729@qq.com
  bio: "明朝即長路 惜取此時心"

# Data
gavatar: img/lala.jpg
favicon: img/bitbug_favicon.ico

douban_username: czr
twitter_username: czr  
github_username: 2016caicai  
facebook_username: czr  
weibo_username: czr  
zhihu_username: czr  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: czr/guanzhou

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "czr"
      header-img: "img/lala.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : czr
  disqus :
      short_name : czr

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
